let test = require('ava')

test('foo', t => t.pass())
test('foo', t => t.pass())
test('foo', t => t.pass())
test('foo', t => t.pass())
test('foo', t => t.pass())
test('foo', t => t.pass())
test('foo', t => t.pass())
test('foo', t => t.pass())
test('foo', t => t.pass())
test('foo', t => t.pass())
